services:
    server:
        build:
            context: .
        ports:
            - 43210:43210
        environment:
            # TODO: goerli, sepolia, blast-sepolia...
            BLAST_RPC: $BLAST_RPC
            BLAST_WSS: $BLAST_WSS
            API_NETWORK: $API_NETWORK
            API_DB_URL: postgres://postgres:let-me-in@postgres/api
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres:16
        restart: always
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=let-me-in
            - POSTGRES_DB=api
        ports:
            - 5432:5432
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5
